apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster.k8slabs.tk
  name: master-us-east-2a
spec:
  cloudLabels:
    environment: k8slabs
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3.small
  maxPrice: "0.007"
  maxSize: 1
  minSize: 1
  rootVolumeSize: 20
  role: Master
  subnets:
  - public-us-east-2a
# ---
# apiVersion: kops/v1alpha2
# kind: InstanceGroup
# metadata:
#   labels:
#     kops.k8s.io/cluster: cluster.k8slabs.tk
#   name: master-us-east-2b
# spec:
#   cloudLabels:
#     environment: k8slabs
#   image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
#   machineType: t2.micro
#   maxSize: 1
#   minSize: 1
#   rootVolumeSize: 8
#   role: Master
#   subnets:
#   - public-us-east-2b
# ---
# apiVersion: kops/v1alpha2
# kind: InstanceGroup
# metadata:
#   labels:
#     kops.k8s.io/cluster: cluster.k8slabs.tk
#   name: master-us-east-2c
# spec:
#   cloudLabels:
#     environment: k8slabs
#   image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
#   machineType: t2.micro
#   maxSize: 1
#   minSize: 1
#   rootVolumeSize: 8
#   role: Master
#   subnets:
#   - public-us-east-2c