apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster.k8slabs.tk
  name: nodes-free-tier
spec:
  cloudLabels:
    environment: k8slabs
    k8s.io/cluster-autoscaler/enabled: "1"
    kubernetes.io/cluster/cluster.k8slabs.tk: "1"
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.micro
  maxSize: 3
  minSize: 1
  rootVolumeSize: 16
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-free-tier
  role: Node
  subnets:
  - public-us-east-2a
  - public-us-east-2b
  - public-us-east-2c